### PR TITLE
Added support for scala 2.11

### PR DESCRIPTION
**Pull request by weicheng113**
Please add support for scala 2.11, so that people who using spark for example can use the library.

### CODE REVIEW

**Comment by takezoe** [comment]
Failed to compile with Scala 2.11. The current scala-retry codebase seems to not compatible with Scala 2.11.
```
[error] /Users/takezoe/scala-retry/src/main/scala/com/github/takezoe/retry/CircuitBreakerPolicy.scala:13:1: identifier expected but ')' found.
[error] )
[error] ^
[error] /Users/takezoe/scala-retry/src/main/scala/com/github/takezoe/retry/CircuitBreakerPolicy.scala:115:2: ':' expected but eof found.
[error] }
[error]  ^
[error] two errors found
```

**Comment by takezoe** [comment]
Another compilation error with Scala 2.11:
```
[error] /Users/takezoe/scala-retry/src/main/scala/com/github/takezoe/retry/FutureRetryManager.scala:20:67: type mismatch;
[error]  found   : com.github.takezoe.retry.FutureRetryTask => Unit
[error]  required: java.util.function.Consumer[_ >: com.github.takezoe.retry.FutureRetryTask]
[error]         tasks.iterator().forEachRemaining { task: FutureRetryTask =>
[error]
```

**Comment by takezoe** [comment]
@weicheng113 In addition to adding Scala 2.11 to crossScalaVersions, the following changes will make scala-retry Scala 2.11 compatibe. Would you include these changes in this pull request?
```diff
diff --git a/build.sbt b/build.sbt
index 541b319..de35737 100644
--- a/build.sbt
+++ b/build.sbt
@@ -6,7 +6,7 @@ version := "0.0.4"

 scalaVersion := "2.12.11"

-crossScalaVersions := Seq("2.12.11", "2.13.1", "2.11.12")
+crossScalaVersions := Seq("2.12.11", "2.13.2", "2.11.12")

 libraryDependencies ++= Seq(
   "org.scalatest" %% "scalatest" % "3.0.8" % "test"
diff --git a/src/main/scala/com/github/takezoe/retry/CircuitBreakerPolicy.scala b/src/main/scala/com/github/takezoe/retry/CircuitBreakerPolicy.scala
index a917fbd..6aba8db 100644
--- a/src/main/scala/com/github/takezoe/retry/CircuitBreakerPolicy.scala
+++ b/src/main/scala/com/github/takezoe/retry/CircuitBreakerPolicy.scala
@@ -9,7 +9,7 @@ case class CircuitBreakerContext(
   state: State = Close,
   failureCount: Int = 0,
   successCount: Int = 0,
-  lastFailure: Option[FailureInfo] = None,
+  lastFailure: Option[FailureInfo] = None
 )

 case class FailureInfo(
diff --git a/src/main/scala/com/github/takezoe/retry/FutureRetryManager.scala b/src/main/scala/com/github/takezoe/retry/FutureRetryManager.scala
index e3a3a05..f7cbca4 100644
--- a/src/main/scala/com/github/takezoe/retry/FutureRetryManager.scala
+++ b/src/main/scala/com/github/takezoe/retry/FutureRetryManager.scala
@@ -6,6 +6,7 @@ import java.util.concurrent.atomic.AtomicBoolean
 import scala.concurrent.{ExecutionContext, Future, Promise}
 import scala.util.control.NonFatal
 import scala.util.{Failure, Success}
+import java.util.function.Consumer

 class RetryManager {

@@ -17,27 +18,29 @@ class RetryManager {
     override def run(): Unit = {
       while(running.get()){
         val currentTime = System.currentTimeMillis
-        tasks.iterator().forEachRemaining { task =>
-          if(task.nextRun <= currentTime){
-            tasks.remove(task)
-            val future = task.f()
-            future.onComplete {
-              case Success(v) => task.promise.success(v)
-              case Failure(e) => {
-                if(task.count == task.policy.maxAttempts){
-                  task.policy.onFailure(RetryContext(task.count + 1, e))
-                  task.promise.failure(e)
-                } else {
-                  task.policy.onRetry(RetryContext(task.count + 1, e))
-                  val count = task.count + 1
-                  val nextDuration = task.policy.backOff.nextDuration(count, task.policy.retryDuration.toMillis)
-                  val nextRun = currentTime + nextDuration + jitter(task.policy.jitter.toMillis)
-                  tasks.add(new FutureRetryTask(task.f, task.policy, task.ec, task.promise, nextRun, count))
+        tasks.iterator().forEachRemaining(new Consumer[FutureRetryTask]{
+          override def accept(task: FutureRetryTask): Unit = {
+            if(task.nextRun <= currentTime){
+              tasks.remove(task)
+              val future = task.f()
+              future.onComplete {
+                case Success(v) => task.promise.success(v)
+                case Failure(e) => {
+                  if(task.count == task.policy.maxAttempts){
+                    task.policy.onFailure(RetryContext(task.count + 1, e))
+                    task.promise.failure(e)
+                  } else {
+                    task.policy.onRetry(RetryContext(task.count + 1, e))
+                    val count = task.count + 1
+                    val nextDuration = task.policy.backOff.nextDuration(count, task.policy.retryDuration.toMillis)
+                    val nextRun = currentTime + nextDuration + jitter(task.policy.jitter.toMillis)
+                    tasks.add(new FutureRetryTask(task.f, task.policy, task.ec, task.promise, nextRun, count))
+                  }
                 }
-              }
-            }(task.ec)
+              }(task.ec)
+            }
           }
-        }
+        })
       }
       Thread.sleep(100)
     }
```

**Comment by weicheng113** [comment]
Hi Naoki,

Thanks, I will do that on Monday.

Naoki Takezoe <notifications@github.com> 于2020年5月9日周六 上午5:28写道：

**Comment by weicheng113** [comment]
@takezoe sorry, I am busy these days. Please use your own 2.11 updated code.

**Comment by takezoe** [comment]
Scala 2.11 support is added in https://github.com/takezoe/scala-retry/commit/7f94f66642e2252f536b133db77b8cf6f9ca7403
